# Generated by Django 5.0.7 on 2026-06-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_alter_moodoption_id_alter_moodquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodoption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moodquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
