# Generated by Django 6.0.6 on 2026-06-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_alter_moodoption_id_alter_moodquestion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moodquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
